# Copyright (c) 2025 Henru Wang
# All rights reserved.

name: Bug Report
description: Report a bug discovered during implementation or usage
title: "[Bug]: "
labels: ["bug", "initial"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: input
    id: tdd-section
    attributes:
      label: TDD Section Reference (if known)
      description: Link to the relevant TDD section where this functionality is specified. If unknown, describe the affected feature and we'll help identify it.
      placeholder: "Section X.X.X or docs/tdd.md#heading, or describe the feature area"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0, Windows 11]
        - Python version: [e.g., 3.11.5]
        - Package version: [e.g., 0.0.5]
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Relevant error messages, stack traces, or log output
      placeholder: Paste error logs here
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
    validations:
      required: false
